name: openfe-notebooks
channels:
  - conda-forge
dependencies:
  - coverage
  - ipywidgets
  - lxml
  - nbval
  - nglview
  - notebook
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python
  - openff-interchange-base != 0.5.1  # https://github.com/openforcefield/openff-interchange/issues/1450
  - pip:
    - git+https://github.com/OpenFreeEnergy/gufe@main
    - git+https://github.com/OpenFreeEnergy/openfe@membrane_prototype
