name: openfe-notebooks
channels:
  - conda-forge
dependencies:
  - coverage
  - ipywidgets
  - lxml
  - nbval
  - nglview
  - notebook
  - numpy
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python=3.13
  # - openfe==1.12.0
  
  # tmp for dev build until openfe 1.13 is released
  - gufe == 1.13.0
  - cinnabar >=0.6.0
  - kartograf ~=2.0
  - konnektor ~=0.5.0
  - openfe-analysis>=0.5.0
  - lomap2>=3.2.1
  - openmmforcefields >=0.15.1  # min needed for https://github.com/openmm/openmmforcefields/pull/414
  - openmmtools >=0.26  # fix to support membrane barostat: https://github.com/choderalab/openmmtools/pull/798
  - plugcli

  - pip:
    - git+https://github.com/OpenFreeEnergy/openfe@main # use conda-forge v1.13.0 after release
