name: openfe-notebooks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
  - openeye
dependencies:
  - MDAnalysis
  - click
  - coverage
  - ipywidgets==7.*
  - lomap2
  - lxml
  - mdtraj
  - nbval
  - networkx
  - nglview
  - notebook
  - openff-forcefields
  - openmm
  - openmmtools
  - pip
  - plugcli
  - pymbar
  - pytest
  - pytest-cov
  - pytest-xdist
  - pydantic
  - python==3.9.*
  - rdkit
  - typing_extensions
  - gufe==0.6.*
  - openfe==0.6.*
  ## needed for perses
  - openmoltools
  - cloudpathlib
  - dask
  - distributed
  - openeye-toolkits


