name: openfe-notebooks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - MDAnalysis
  - click
  - coverage
  - gufe==0.2
  - lomap2
  - mdtraj
  - nbval
  - networkx
  - nglview
  - notebook
  - numpy
  - openfe==0.3
  - openff-forcefields
  - openff-toolkit
  - openmm
  - openmmforcefields==0.10.0
  - openmmtools
  - pip
  - plugcli
  - pymbar
  - pytest
  - pytest-cov
  - pytest-xdist
  - pydantic
  - python==3.9
  - rdkit
  - typing_extensions
