name: openfe-notebooks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - MDAnalysis
  - click
  - coverage
  - mdtraj
  - nbval
  - networkx
  - nglview
  - notebook
  - numpy
  - openff-forcefields
  - openff-toolkit
  - openff-toolkit
  - openff-toolkit
  - openmm
  - openmmforcefields
  - openmmforcefields
  - openmmtools
  - pip
  - pymbar
  - python==3.9
  - pytest
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-xdist
  - rdkit
  - pip:
    - git+https://github.com/OpenFreeEnergy/Lomap@v2.0-alpha
    - plugcli
    - cyjupyter
    - git+https://github.com/OpenFreeEnergy/openfe@v0.1
