name: openfe-notebooks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge/label/openfe_rc
  - conda-forge/label/gufe_rc
  - conda-forge
dependencies:
  - MDAnalysis
  - click
  - coverage
  - ipywidgets
  - lomap2
  - lxml
  - mdtraj
  - nbval
  - networkx
  - nglview
  - notebook
  - openff-forcefields
  - openmm
  - openmmtools>=0.23.0
  - pip
  - plugcli
  - pymbar
  - pytest
  - pytest-cov
  - pytest-xdist
  - pydantic
  - python==3.11.*
  - rdkit
  - typing_extensions
  - gufe>=0.9.4
  - openfe>=1.0.0rc0
  - py3dmol
