name: openfe-notebooks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - MDAnalysis
  - click
  - coverage
  - gufe
  - lomap2
  - mdtraj
  - nbval
  - networkx
  - nglview
  - notebook
  - numpy
  - openff-forcefields
  - openff-toolkit
  - openff-toolkit
  - openff-toolkit
  - openmm
  - openmmforcefields
  - openmmforcefields
  - openmmtools
  - pip
  - plugcli
  - pymbar
  - pytest
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-xdist
  - python==3.9
  - rdkit
  - typing_extensions
  - pip:
    - git+https://github.com/OpenFreeEnergy/openfe@main
