name: openfe-notebooks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - MDAnalysis
  - click
  - coverage
  - ipywidgets==7.*
  - lomap2
  - lxml
  - mdtraj
  - nbval
  - networkx
  - nglview
  - notebook
  - numpy
  - openff-forcefields
  - openff-toolkit==0.10.6
  - openff-units>=0.1.8
  - openmm
  - openmmtools
  - pip
  - plugcli
  - pymbar
  - pytest
  - pytest-cov
  - pytest-xdist
  - pydantic
  - python==3.9
  - rdkit
  - typing_extensions
  - pip:
    - git+https://github.com/OpenFreeEnergy/gufe@main
    - git+https://github.com/openmm/openmmforcefields@main
    - git+https://github.com/OpenFreeEnergy/openfe@main
    - plugcli
