name: openfe-notebooks
channels:
  - conda-forge
dependencies:
  - MDAnalysis
  - click
  - coverage
  - ipywidgets
  - lomap2
  - lxml
  - mdtraj
  - nbval
  - networkx
  - nglview
  - notebook
  - openff-forcefields
  - openmm
  - openmmtools>=0.23.0
  - pip
  - plugcli
  - pymbar
  - pytest
  - pytest-cov
  - pytest-xdist
  - pydantic
  - python
  - rdkit
  - typing_extensions
  - gufe>=1.7.0
  - openfe>=1.7.0
  - py3dmol
