name: openfe-notebooks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - MDAnalysis
  - click
  - coverage
  - ipywidgets==7.*
  - lomap2
  - lxml
  - mdtraj
  - nbval
  - networkx
  - nglview
  - notebook
  - numpy
  - openff-forcefields
  - openff-toolkit==0.11.*
  - openff-units>=0.1.8
  - openmm
  - openmmtools
  - openmmforcefields==0.11.2
  - pip
  - plugcli
  - pymbar
  - pytest
  - pytest-cov
  - pytest-xdist
  - pydantic
  - python==3.9.*
  - rdkit
  - typing_extensions
  - gufe==0.4.*
  - openfe==0.4.*
