name: openfe-notebooks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - MDAnalysis
  - click
  - coverage
  - ipywidgets==7.*
  - lomap2
  - lxml
  - mdtraj
  - nbval
  - networkx
  - nglview
  - notebook
  - openff-forcefields
  - openmm
  - openmmtools
  - pip
  - plugcli
  - pymbar
  - pytest
  - pytest-cov
  - pytest-xdist
  - pydantic
  - python==3.9.*
  - rdkit
  - typing_extensions
  - gufe>=0.7.1
  - openfe>=0.7.1
