name: openfe-notebooks
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  # setup
  - openmm
  - openmmforcefields
  - openff-toolkit
  # CI
  - pytest
  - pytest-xdist
  - nbval
