#./.github/workflows/colab-badge.yaml
name: Colab Badge
on: 
  pull_request_target:
    types: [opened]

jobs:
  colab:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: comment on PR with Colab link
      uses: actions/github-script@v8
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var PR_HEAD_USERREPO = process.env.PR_HEAD_USERREPO;
          var PR_HEAD_REF = process.env.PR_HEAD_REF;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `[![Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/OpenFreeEnergy/ExampleNotebooks/blob/${PR_HEAD_REF}/showcase)) :point_left: Launch a Colab session on branch _${PR_HEAD_REF}_`
          })
      env:
        PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        PR_HEAD_USERREPO: ${{ github.event.pull_request.head.repo.full_name }}
