name: full_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # nightly tests, 2 am
    - cron: "0 2 * * *"

concurrency:
  # Probably overly cautious group naming.
  # Commits to develop/master will cancel each other, but PRs will only cancel
  # commits within the same PR
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true


defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12]
        python-version: ["3.11",]

    steps:
    - uses: actions/checkout@v2.4.0
    
    - name: Get current date
      id: date
      run: echo "date=$(date +%Y-%m-%d)" >> "${GITHUB_OUTPUT}"

    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: .binder/environment.yml
        cache-environment: true
        cache-downloads: true
        cache-environment-key: environment-${{ steps.date.outputs.date }}
        cache-downloads-key: downloads-${{ steps.date.outputs.date }}
        create-args: >-
          python=${{ matrix.python-version }}
        init-shell: bash

    - name: Additional info about the build
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Environment Information
      run: |
        conda info
        conda list

    - name: Run example notebooks
      run: |
        python -m pytest -v setup/ openmm_rbfe/ networks/ --nbval-lax -n auto --dist loadscope
