name: full_tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    # nightly tests, 2 am
    - cron: "0 2 * * *"

concurrency:
  # Probably overly cautious group naming.
  # Commits to develop/master will cancel each other, but PRs will only cancel
  # commits within the same PR
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true


defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15, macos-11]
        python-version: ["3.8", "3.9",]

    steps:
    - uses: actions/checkout@v2.4.0

    - uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        python-version: "${{ matrix.python-version }}"
        environment-file: .binder/environment.yml
        activate-environment: test
        auto-activate-base: false
        mamba-version: "*"
        miniforge-version: latest
        miniforge-variant: Mambaforge
        use-mamba: true
        channel-priority: true

    - name: Additional info about the build
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Environment Information
      run: |
        conda info
        conda list

    - name: Run example notebooks
      run: |
        python -m pytest -v setup/ --nbval-lax -n auto --dist loadscope
